name: Application Build & Deploy Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/financial-news-analyzer:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/financial-news-analyzer:latest

  deploy:
    needs: build_and_push_docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/financial-news-analyzer:latest
            docker stop financial-news-analyzer || true
            docker rm financial-news-analyzer || true
            docker run -d --name financial-news-analyzer -p 8000:8000 \
            -e MLFLOW_TRACKING_URI="http://10.0.0.5:5000" \
            -e MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }} \
            -e MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }} \
            ${{ secrets.DOCKER_USERNAME }}/financial-news-analyzer:latest